### PR TITLE
Ignore cache-loader directory when publishing

### PR DESCRIPTION
**Pull request by filipesilva**
Currently `.cache-loader` is being published, with some local data from tests: https://unpkg.com/happypack@4.0.0/.cache-loader/

### CODE REVIEW

**Comment by amireh** [comment]
Nice catch, thanks.

Since something similar happened in the past, what do you think about adopting a whitelist approach instead? IIRC package.json allows a [files](https://docs.npmjs.com/files/package.json#files) listing that can be used for this purpose.

**Comment by filipesilva** [comment]
That seems reasonable as well. In that case `.npm-ignore` would be deleted and files would look like this:
```
"files": [
  "lib",
  "loader.js",
  "CHANGELOG.md",
  "README.md"
],
```

This represents a problem with the `/lib/__tests__` ignore rule though. To ignore it, a new `./lib/.npmignore` will need to be added with just `/lib/__tests__`, because of this:
> You can also provide a .npmignore file in the root of your package or in subdirectories, which will keep files from being included. At the root of your package it will not override the "files" field, but in subdirectories it will. 

WDYT?

**Comment by amireh** [comment]
I'm thinking maybe we can move the tests outside of lib altogether, but I can do that in a separate patchset.

The following looks good to me (dirs first then files, in alphabetical order):

```javascript
"files": [
    "lib",
    "CHANGELOG.md",
    "LICENSE",
    "loader.js",
    "README.md"
  ],
```

I just tested that and it tars at 25K with the proper files (assuming you use `.npmignore` inside `lib/`.)

**Comment by filipesilva** [comment]
@amireh added the files array as you listed, and moved `.npmignore` with only the tests entry.

**Comment by amireh** [comment]
Looks good to me, gonna pull it down to double-check.

**Comment by amireh** [comment]
@filipesilva thanks, will publish a new revision shortly!

**Comment by filipesilva** [comment]
Coolio, thanks for the quick turnaround!

**Comment by amireh** [comment]
Version 4.0.1 is now up on npm with this change

**Pull request merged**
