### PR TITLE
Updated Readme removing incompatibily w/ Webpack2

### PR DESCRIPTION
**Pull request by welll**
This PR could closes the Issue #146.

### CODE REVIEW

**Comment by welll** [comment]
@amireh could you take a look on it? this PR will close the Issue #146.

**Comment by amireh** [comment]
I'm not sure I want to make this change since I've stopped using webpack 2 and went back to webpack 1. I have no intention of maintaining webpack 2 support for this project, so unless someone else wants to do it it's gonna stay like it is.

Thanks for the contribution though!

**Comment by welll** [comment]
I totally agree with you ;)
Can I candidate myself to start the webpack2 support?

I can start taking a look into this `https://github.com/amireh/happypack/issues/143`.
What do you think?

**Comment by amireh** [comment]
@welll of course, if you feel you're up to it then please be my guest. Let me know if you need any help.

**Pull request closed without merging**
