### PR TITLE
Fallback  to existsSync when accessSync is not there

### PR DESCRIPTION
**Pull request by XVincentX**
This should solve #13

### CODE REVIEW

**Comment by amireh** [comment]
Nice catch! It's sad how that error was not being caught easily...

Will merge once it passes CI (which doesn't really guarantee anything for node 0.10 since I had to remove those versions off from the build matrix.)

**Comment by amireh** [comment]
I think you should run `npm run lint` locally. A bit opinionated but keeps things clean.

**Comment by XVincentX** [comment]
I ran lint and it is passing; let me check the tests.

**Comment by amireh** [comment]
I'll correct this locally

**Comment by XVincentX** [comment]
@amireh It should be ready now. It would be great if you could merge/publish it now and free me from wasting time!

**Comment by amireh** [comment]
Will do!

**Comment by amireh** [comment]
@XVincentX 2.0.4 is on NPM and includes your change.

**Comment by XVincentX** [comment]
Whoooooooooooooo!

**Pull request merged**
